name: Start PostgreSQL Server

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  start-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start PostgreSQL Server
        run: |
          az postgres flexible-server start \
            --resource-group 17032026 \
            --name bajiserver0